workers:
  - name: configuration
    config:
      adapter:
        name: fs
        config:
          directory: /data/config
  - name: iii-worker-manager
    config:
      port: ${III_ENGINE_PORT:49134}
      host: 0.0.0.0
  - name: iii-http-functions
    config: {}
  - name: iii-stream
    config:
      port: ${III_STREAM_PORT:3112}
      host: 0.0.0.0
      adapter:
        name: kv
        config:
          store_method: file_based
          file_path: /data/stream_store
